5.1.0

diff --git a/ossim-menu-setup/lib/update-system b/ossim-menu-setup/lib/update-system
--- a/ossim-menu-setup/lib/update-system
+++ b/ossim-menu-setup/lib/update-system
@@ -29,10 +29,10 @@ ERROR_STRING=( "Successful update"
 "Error installing mailbsdx"
 "Error while downloading packages prior to a dist-upgrade operation"
 "Error during a dist-upgrade operation"
-"Error while updating igb-pfring"
 "Error while uninstalling squid2"
 "Error while autoremoving unnecessary packages"
-"Error while purging files/packages not needed any more")
+"Error while purging files/packages not needed any more"
+"Update still not available for this platform")
 
 ALIENVAULT_UPDATE_ERROR_STRING=( "Error: There is an update instance running. Aborting update"
 "Error: Invalid signature for upgrade file (AV3)"
@@ -43,9 +43,10 @@ ALIENVAULT_UPDATE_ERROR_STRING=( "Error: There is an update instance running. Ab
 "Error: Signature unavailable for upgrade file (AV4)"
 "Error: Invalid signature for upgrade file (feed)"
 "Error: Signature unavailable for upgrade file (feed)"
-"Error: System running in HA Mode. Aborting update")
-
-REBOOT_NEEDED_FILE="/tmp/.reboot_needed"
+"Error: System running in HA Mode. Aborting update"
+"Error: Cannot download upgrade file (AV5)"
+"Error: Invalid signature for upgrade file (AV5)"
+"Error: Signature unavailable for upgrade file (AV5)")
 
 function update_system() {
     dpkg -l alienvault-dummy-framework | grep ^i > /dev/null
@@ -62,19 +63,118 @@ function update_system() {
 
     alienvault-update
 
-    # Check new kernel version (if available)
-    RUNNING_KERNEL_VERSION=$(grep -Eo "^Linux\sversion\s\S+\s\(Debian\s[0-9]+\.[0-9]+\.[0-9]+\-[0-9]+[a-z]+[0-9]+" /proc/version | awk '{ print $5 }')
-    INSTALLED_KERNEL_VERSION=$(dpkg-query -l 'linux-image-*-amd64' | grep -E "^(ii|hi)" | grep -vE "(metapackage|meta-package)" | awk '{print $3}')
+    code=$?
 
-    if [ "$RUNNING_KERNEL_VERSION" != "$INSTALLED_KERNEL_VERSION" ]; then
+    check_reboot_needed
+
+    handle_exit $code
+
+    dpkg -l alienvault-dummy-framework|grep ^i > /dev/null
+    if [ $? -eq 0 ]; then
+        invoke-rc.d apache2 start
+    fi
+
+    
+}
+
+function update_system_major() {
+    wget_useragent=$(/usr/bin/alienvault-useragent)
+    tmppath="/usr/share/ossim-installer/temp"
+
+    dataserver="http://data.alienvault.com"
+    REL3="RELEASES"
+    script_name="alienvault5_update-script"
+
+    [ -f "$tmppath/$script_name" ] && rm "$tmppath/$script_name"
+    [ -f "$tmppath/$script_name.sig" ] && rm "$tmppath/$script_name.sig"
+
+    wget -U "$wget_useragent" -O $tmppath/$script_name $dataserver/$REL3/$script_name
+    if [ -s "$tmppath/$script_name" ]
+    then
+        wget -U "$wget_useragent" -O $tmppath/$script_name.sig $dataserver/$REL3/$script_name.sig
+        if [ -s "$tmppath/$script_name.sig" ]
+	    then
+            if gpg --verify --keyring /etc/apt/trusted.gpg $tmppath/$script_name.sig
+            then
+                /bin/bash $tmppath/$script_name
+                handle_exit $?
+            else
+                handle_exit 61
+	    fi
+        else
+            handle_exit 62
+        fi
+    else
+        handle_exit 60
+    fi
+}
+
+function update_system_offline() {
+
+    devname=$(fdisk -l 2>&1 | grep contain | awk '{ print $2 }' | awk -F'/' '{ print $3 }')
+    mkdir -p /media/$devname
+    mount /dev/$devname /media/$devname
+    update_command=$(find /media -maxdepth 2 -name av_offline_update.sh)
+    if [ -n "$update_command" ]; then
+        /bin/bash $update_command  --offline --verbose
+        update_result=$?
+        umount /dev/$devname
+        handle_exit $update_result
+    else
+        # No update script in the device --> error 40
+        umount /dev/$devname
+        handle_exit 40
+    fi
+}
+
+function analyze_update() {
+    echo "OOOOOPS: There was an error updating the system"
+    [ -f /etc/ossim/.update_result ] && cat "/etc/ossim/.update_result" || true
+    rm -f "/etc/ossim/.update_result"
+}
+
+function check_reboot_needed() {
+    REBOOT_NEEDED_FILE="/tmp/.reboot_needed"
+
+    RAW_RUNNING_KERNEL_VERSION=$(cat /proc/version)
+
+    if [[ $RAW_RUNNING_KERNEL_VERSION == 'Linux version 2.6.'* ]]
+    then
+        RUNNING_KERNEL_VERSION=$(grep -Eo "^Linux\sversion\s\S+\s\(Debian\s([^\)]*)" /proc/version | awk '{ print $5 }')
+    elif [[ $RAW_RUNNING_KERNEL_VERSION == 'Linux version 3.2.'* ]]
+    then
+        RUNNING_KERNEL_VERSION=$(cat /proc/version | awk '{print $NF}')
+    elif [[ $RAW_RUNNING_KERNEL_VERSION == 'Linux version 3.16.'* ]]
+    then
+        RUNNING_KERNEL_VERSION=$(cat /proc/version | awk '{print $(NF-1)}')
+    else
+        echo "Unknown kernel version, reboot will be requested"
+        RUNNING_KERNEL_VERSION="0.0.0"
+    fi
+
+    INSTALLED_KERNEL_VERSION=$(dpkg-query -l 'linux-image-*-amd64' | grep -E "^(ii|hi)" | grep -vE "(metapackage|meta-package)" | awk '{print $3}')
+    LATEST_INSTALLED_KERNEL_VERSION="0"
+        
+    for item in $INSTALLED_KERNEL_VERSION; do
+        if $(dpkg --compare-versions $LATEST_INSTALLED_KERNEL_VERSION lt $item)
+        then
+            LATEST_INSTALLED_KERNEL_VERSION=$item
+        fi
+    done
+
+    if [ "$RUNNING_KERNEL_VERSION" != "$LATEST_INSTALLED_KERNEL_VERSION" ]
+    then
         touch $REBOOT_NEEDED_FILE
         chown www-data:alienvault $REBOOT_NEEDED_FILE
         chmod 0660 $REBOOT_NEEDED_FILE
     fi
+}
 
-    code=$?
+function handle_exit() {
+    code=$1
+
     case "$code" in
-        50|51|52|53|54|55|56|57|58|59)
+         50|51|52|53|54|55|56|57|58|59|60|61|62)
             aux_code=$(( code - 50 ))
             echo ${ALIENVAULT_UPDATE_ERROR_STRING[aux_code]} > "/etc/ossim/.update_result"
             exit $code
@@ -86,23 +186,11 @@ function update_system() {
             fi
             ;;
     esac
-
-    dpkg -l alienvault-dummy-framework|grep ^i > /dev/null
-    if [ $? -eq 0 ]; then
-        invoke-rc.d apache2 start
-    fi
-
-    
-}
-
-function analyze_update() {
-
-    echo "OOOOOPS: There was an error updating the system"
-    [ -f /etc/ossim/.update_result ] && cat "/etc/ossim/.update_result" || true
-    rm -f "/etc/ossim/.update_result"
 }
 
 [ $1 == "--us" ] && update_system
+[ $1 == "--usm" ] && update_system_major
+[ $1 == "--uso" ] && update_system_offline
 [ $1 == "--au" ] && analyze_update
 
 exit 0
