4.15.2 from https://www.alienvault.com/open-threat-exchange/projects with md5 415b6cbe1c1e4919770cbc0081e92089

diff --git a/alienvault-api/alienvault-api/api/scripts/celerybeat b/alienvault-api/alienvault-api/api/scripts/celerybeat
--- a/alienvault-api/alienvault-api/api/scripts/celerybeat
+++ b/alienvault-api/alienvault-api/api/scripts/celerybeat
@@ -20,8 +20,9 @@
 # Cannot use set -e/bash -e since the kill -0 command will abort
 # abnormally in the absence of a valid process ID.
 #set -e
-
-DEFAULT_PID_FILE=/var/run/alienvault/beat.pid
+DEFAULT_RUN_DIR=/var/run
+DEFAULT_PID_DIR=$DEFAULT_RUN_DIR/alienvault
+DEFAULT_PID_FILE=$DEFAULT_PID_DIR/beat.pid
 DEFAULT_LOG_FILE=/var/log/alienvault/api/celerybeat.log
 DEFAULT_LOG_LEVEL="INFO"
 DEFAULT_CELERYBEAT=/usr/share/alienvault/api_core/bin/celerybeat
@@ -109,19 +110,54 @@ create_default_dir() {
     fi
 }
 
+
 check_paths() {
     if [ $CELERY_CREATE_LOGDIR -eq 1 ]; then
         create_default_dir "$CELERYBEAT_LOG_DIR"
     fi
+
     if [ $CELERY_CREATE_RUNDIR -eq 1 ]; then
-        create_default_dir "$CELERYBEAT_PID_DIR"
+        if [ -h $DEFAULT_RUN_DIR ]; then
+            # Wheezy
+            mount | grep "/run type"
+            if [ "$?" != "1" ]; then
+                if [ ! -d $CELERYBEAT_PID_DIR ]; then
+                    create_default_dir "$CELERYBEAT_PID_DIR"
+                fi
+            else
+                log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
+                exit 1
+            fi
+        else
+            # Squeeze
+            if [ ! -d $CELERYBEAT_PID_DIR ]; then
+                create_default_dir "$CELERYBEAT_PID_DIR"
+            fi
+        fi
     fi
 }
 
 
 create_paths () {
     create_default_dir "$CELERYBEAT_LOG_DIR"
-    create_default_dir "$CELERYBEAT_PID_DIR"
+
+    if [ -h $DEFAULT_RUN_DIR ]; then
+        # Wheezy
+        mount | grep "/run type"
+        if [ "$?" != "1" ]; then
+            if [ ! -d $CELERYBEAT_PID_DIR ]; then
+                create_default_dir "$CELERYBEAT_PID_DIR"
+            fi
+        else
+            log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
+            exit 1
+        fi
+    else
+        # Squeeze
+        if [ ! -d $CELERYBEAT_PID_DIR ]; then
+            create_default_dir "$CELERYBEAT_PID_DIR"
+        fi
+    fi
 }
 
 
diff --git a/alienvault-dummies-config/debian/alienvault-firewall.postinst b/alienvault-dummies-config/debian/alienvault-firewall.postinst
--- a/alienvault-dummies-config/debian/alienvault-firewall.postinst
+++ b/alienvault-dummies-config/debian/alienvault-firewall.postinst
@@ -26,35 +26,49 @@ TMP_TEST_RULES_RESULT="/tmp/ofv.tmp"
 VALID_FIREWALL_CUSTOM_RULES="/etc/iptables/rules012-custom.iptables"
 DEPRECATED_FIREWALL_RULES="/etc/ossim_firewall"
 DEPRECATED_FIREWALL_IP6_RULES="/etc/ossim_firewall_ipv6"
+
+LAST_INPUT_RULE="-A INPUT -j REJECT --reject-with icmp-host-prohibited"
+LAST_FORWARD_RULE="-A FORWARD -j REJECT --reject-with icmp-host-prohibited"
  
 configure_firewall(){
     # Prepares the custom rules added by the user in the firewall_include file
     # to make them be applied in the firewall configuration file
       
     if [ -f $CUSTOM_FIREWALL_RULES ]; then
-        echo "*filter" > $TMP_FIREWALL_CUSTOM_RULES
-        { cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" >> $TMP_FIREWALL_CUSTOM_RULES ; } || true
-        echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited
-COMMIT" >> $TMP_FIREWALL_CUSTOM_RULES
+        length=$(sed -e "s/^#.*$//g" "$CUSTOM_FIREWALL_RULES")
+        if [ ! -z "$length" ]; then
+            cat $(ls /etc/iptables/*.iptables | grep -v ip6) | grep -v COMMIT > $TMP_FIREWALL_CUSTOM_RULES
+            cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" >> $TMP_FIREWALL_CUSTOM_RULES || true
+            echo "COMMIT" >> $TMP_FIREWALL_CUSTOM_RULES
 
-        if [ -f $TMP_TEST_RULES_RESULT ]; then
-            cat "$TMP_FIREWALL_CUSTOM_RULES" | grep -v filter | grep -v COMMIT > $VALID_FIREWALL_CUSTOM_RULES
-            rm -rf $TMP_FIREWALL_CUSTOM_RULES
-            rm -rf $TMP_TEST_RULES_RESULT
+            /sbin/iptables-restore --test $TMP_FIREWALL_CUSTOM_RULES && echo "yes" > $TMP_TEST_RULES_RESULT || true
+
+            if [ -f $TMP_TEST_RULES_RESULT ]; then
+                echo "Custom firewall rules tested successfully"
+                cat "$CUSTOM_FIREWALL_RULES" | grep -v "^#" > $VALID_FIREWALL_CUSTOM_RULES || true
+                echo "$LAST_INPUT_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
+                echo "$LAST_FORWARD_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
+                rm -rf $TMP_FIREWALL_CUSTOM_RULES
+                rm -rf $TMP_TEST_RULES_RESULT
+            else
+                echo "Custom firewall rules test failed. Custom rules will be ignored"
+                # There is no need to append "COMMIT", since it is included in zzzzz-footer.iptables
+                echo "$LAST_INPUT_RULE" > "$VALID_FIREWALL_CUSTOM_RULES"
+                echo "$LAST_FORWARD_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
+            fi
         else
-            # There is no need to append "COMMIT", since it is included in zzzzz-footer.iptables
-            echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited" > $VALID_FIREWALL_CUSTOM_RULES
+            echo "$LAST_INPUT_RULE" > "$VALID_FIREWALL_CUSTOM_RULES"
+            echo "$LAST_FORWARD_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
         fi
-
     else
-        echo "-A INPUT -j REJECT --reject-with icmp-host-prohibited
--A FORWARD -j REJECT --reject-with icmp-host-prohibited" >> $VALID_FIREWALL_CUSTOM_RULES
+        echo "$LAST_INPUT_RULE" > "$VALID_FIREWALL_CUSTOM_RULES"
+        echo "$LAST_FORWARD_RULE" >> "$VALID_FIREWALL_CUSTOM_RULES"
     fi
 
     /etc/network/if-pre-up.d/iptables > /dev/null 2>&1 || true
 }
+
+
 
 delete_deprecated_firewall_configuration(){
     # Removes the deprecated firewall configuration from the system
diff --git a/alienvault-dummies-config/debian/alienvault-mysql.postinst b/alienvault-dummies-config/debian/alienvault-mysql.postinst
--- a/alienvault-dummies-config/debian/alienvault-mysql.postinst
+++ b/alienvault-dummies-config/debian/alienvault-mysql.postinst
@@ -18,16 +18,298 @@ set -e
 # the debian-policy package
 
 OSSIM_SETUP_CONF="/etc/ossim/ossim_setup.conf"
+OSSIM_SETUP_CONF_LAST="/etc/ossim/ossim_setup.conf_last"
 DB_FIREWALL_CONF="/etc/iptables/rules006-mysql.iptables"
+MYSQL_CONF_FILE="/etc/mysql/my.cnf"
 
-get_ossim_param_value(){
+get_ossim_param_value() {
     mypattern="^$1="
-    value=$(egrep "$mypattern" "$OSSIM_SETUP_CONF" | cut -d'=' -f2)
+    [ "$2" = "last" ] && ossim_conf=$OSSIM_SETUP_CONF_LAST || ossim_conf=$OSSIM_SETUP_CONF
+
+    value=$(egrep "$mypattern" "$ossim_conf" | cut -d'=' -f2)
     echo $value
 }
 
+stop_mysql() {
+    db_ip=`get_ossim_param_value "db_ip"`
+
+    set +e
+
+    retry=0
+    until ! echo exit | ossim-db mysql; do
+        [ 8 -le $retry ] && break
+        if [ ! -f /sbin/start-stop-daemon.REAL ]; then
+            /etc/init.d/mysql stop
+        else
+            echo "Stopping MySQL..."
+            killall -15 mysqld > /dev/null 2>&1
+        fi
+        sleep 5
+        retry=$(( $retry + 1 ))
+    done
+
+    set -e
+}
+
+start_mysql() {
+    db_ip=`get_ossim_param_value "db_ip"`
+    db_pass=`get_ossim_param_value "pass"`
+    db_user=`get_ossim_param_value "user"`
+
+    set +e
+
+    retry=0
+    until echo exit | ossim-db mysql; do
+        [ 8 -le $retry ] && break
+        if [ ! -f /sbin/start-stop-daemon.REAL ]; then
+            /etc/init.d/mysql start
+        else
+            echo "Starting MySQL..."
+            /usr/bin/mysqld_safe > /dev/null 2>&1 &
+            sleep 10
+        fi
+        sleep 5
+        mysqlcheck -h $db_ip -p$db_pass -u $db_user --auto-repair mysql 2>> /tmp/err
+        retry=$(( $retry + 1 ))
+    done
+
+    set -e
+}
+
+reconfigure_mysql() {
+
+    # Profiles installed
+    dpkg --status alienvault-dummy-sensor > /dev/null 2>&1 && sensor=1 || sensor=0
+    dpkg --status alienvault-dummy-database > /dev/null 2>&1 && database=1 || database=0
+    dpkg --status alienvault-dummy-framework > /dev/null 2>&1 && framework=1 ||framework=0
+    dpkg --status alienvault-dummy-server > /dev/null 2>&1 && server=1 || server=0
+
+    # Ha conf
+    ha_conf=`get_ossim_param_value "ha_heartbeat_start"`
+
+    # Total memory in system (in KB)
+    MEM=`cat /proc/meminfo | grep MemTotal | awk '{print $2}'`
+
+    # Default config
+    [ -e "$MYSQL_CONF_FILE" ] && MD5_PRE=`md5sum "$MYSQL_CONF_FILE" | awk '{print $1}'` || MD5_PRE="" # If file not exists sets MD5_PRE to ""
+
+    cat > $MYSQL_CONF_FILE << EOF
+# AlienVault MySQL database server configuration file.
+
+[client]
+port=3306
+socket=/var/run/mysqld/mysqld.sock
+
+[mysqld_safe]
+socket=/var/run/mysqld/mysqld.sock
+nice=0
+
+[mysqld]
+server-id=0
+user=mysql
+pid-file=/var/run/mysqld/mysqld.pid
+socket=/var/run/mysqld/mysqld.sock
+port=3306
+basedir=/usr
+datadir=/var/lib/mysql
+tmpdir=/tmp
+language=/usr/share/mysql/english
+max_allowed_packet=256M
+event_scheduler=ON
+bind-address=0.0.0.0
+key_buffer=16M
+join_buffer_size=128k
+sort_buffer_size=2M
+read_rnd_buffer_size=256k
+max_heap_table_size=16M
+thread_stack=512K
+thread_cache_size=100
+transaction-isolation=READ-COMMITTED
+binlog-format=mixed
+myisam-recover=BACKUP
+max_connections=120
+key_buffer_size=16M
+table_cache=400
+tmp_table_size=16M
+thread_concurrency=10
+concurrent_insert=1
+#skip_name_resolve
+interactive_timeout=28800
+wait_timeout=28800
+slave-skip-errors=OFF
+skip-external-locking
+slave_load_tmpdir=/tmp
+tmpdir=/tmp
+
+# Query Cache Configuration
+query_cache_limit=1M
+query_cache_size=16M
+query_cache_type=1
+
+# Logging and Replication
+#log=/var/log/mysql/mysql.log
+#log_slow_queries=/var/log/mysql/mysql-slow.log
+#long_query_time=2
+#log_bin=/var/log/mysql/mysql-bin.log
+auto_increment_increment=1
+auto_increment_offset=1
+expire_logs_days=10
+max_binlog_size=100M
+#binlog_do_db=include_database_name
+#binlog_ignore_db=include_database_name
+#log-queries-not-using-indexes
+#log_error=/var/log/mysql/error.log
+log_bin_trust_function_creators=OFF
+
+# InnoDB
+innodb_doublewrite_file=/var/lib/mysql/ib_doublewrite
+innodb_file_per_table=1
+innodb_fast_shutdown=0
+innodb_buffer_pool_size=128M
+innodb_additional_mem_pool_size=8M
+#innodb_flush_method=fsync
+innodb_log_buffer_size=8M
+innodb_thread_concurrency=0
+innodb_flush_log_at_trx_commit=1
+innodb_commit_concurrency=0
+innodb_log_file_size=5M
+
+# Security Features
+# chroot=/var/lib/mysql/
+# ssl-ca=/etc/mysql/cacert.pem
+# ssl-cert=/etc/mysql/server-cert.pem
+# ssl-key=/etc/mysql/server-key.pem
+
+[mysqldump]
+quick
+quote-names
+max_allowed_packet=16M
+
+[mysql]
+#no-auto-rehash # faster start of mysql but no tab completition
+
+[isamchk]
+key_buffer=16M
+
+# [MYSQL_CLUSTER]
+# ndb-connectstring=127.0.0.1
+
+#!includedir /etc/mysql/conf.d/
+EOF
+
+    # High memory config
+    if [ $MEM -gt 5000000 ]; then
+        echo "Enabling high memory config..."
+
+        sed -i "s/^innodb_additional_mem_pool_size=.*/innodb_additional_mem_pool_size=20M/" $MYSQL_CONF_FILE
+        sed -i "s/^innodb_buffer_pool_size=.*/innodb_buffer_pool_size=512M/" $MYSQL_CONF_FILE
+        sed -i "s/^innodb_flush_log_at_trx_commit=.*/innodb_flush_log_at_trx_commit=2/" $MYSQL_CONF_FILE
+        sed -i "s/^table_cache=.*/table_cache=1024/" $MYSQL_CONF_FILE
+        sed -i "s/^sort_buffer_size=.*/sort_buffer_size=50M/" $MYSQL_CONF_FILE
+        sed -i "s/^query_cache_limit=.*/query_cache_limit=64M/" $MYSQL_CONF_FILE
+        sed -i "s/^key_buffer_size=.*/key_buffer_size=512M/" $MYSQL_CONF_FILE
+        sed -i "s/^tmp_table_size=.*/tmp_table_size=128M/" $MYSQL_CONF_FILE
+        sed -i "s/^join_buffer_size=.*/join_buffer_size=0/" $MYSQL_CONF_FILE
+        sed -i "s/^thread_concurrency=.*/thread_concurrency=4/" $MYSQL_CONF_FILE
+        sed -i "s/^read_rnd_buffer_size=.*/read_rnd_buffer_size=2M/" $MYSQL_CONF_FILE
+        sed -i "s/^max_heap_table_size=.*/max_heap_table_size=128M/" $MYSQL_CONF_FILE
+        sed -i "s/^concurrent_insert=.*/concurrent_insert=2/" $MYSQL_CONF_FILE
+        sed -i "s/^interactive_timeout=.*/interactive_timeout=300/" $MYSQL_CONF_FILE
+        sed -i "s/^wait_timeout=.*/wait_timeout=300/" $MYSQL_CONF_FILE
+        sed -i "s/^#\?skip_name_resolve.*/skip_name_resolve/" $MYSQL_CONF_FILE
+        sed -i "90 s/^max_allowed_packet=.*/max_allowed_packet=384M/" $MYSQL_CONF_FILE
+        sed -i "96 s/^key_buffer=.*/key_buffer=50M/" $MYSQL_CONF_FILE
+        sed -i "s/^slave_load_tmpdir=.*/slave_load_tmpdir=\/var\/tmp/" $MYSQL_CONF_FILE
+        sed -i "s/^tmpdir=.*/tmpdir=\/var\/tmp/" $MYSQL_CONF_FILE
+        sed -i "s/^query_cache_size=.*/query_cache_size=256M/" $MYSQL_CONF_FILE
+    fi
+
+    # Ha config
+    if [ $ha_conf = "yes" ]; then
+        echo "Enabling ha config..."
+
+        # Server MySQL ID
+        ha_role=`get_ossim_param_value "ha_role"`
+        [ $ha_role = "master" ] && server_mysql_id=1 || server_mysql_id=2
+
+        sed -i "s/^server-id=.*/server-id=$server_mysql_id/" $MYSQL_CONF_FILE
+        sed -i "s/^#\?log_bin=.*/log_bin=\/var\/log\/mysql\/mysql-bin.log/" $MYSQL_CONF_FILE
+        sed -i "s/^auto_increment_increment=.*/auto_increment_increment=2/" $MYSQL_CONF_FILE
+        sed -i "s/^auto_increment_offset=.*/auto_increment_offset=$server_mysql_id/" $MYSQL_CONF_FILE
+        sed -i "s/^#\?log_error=.*/log_error=\/var\/log\/mysql\/error.log/" $MYSQL_CONF_FILE
+        sed -i "s/^slave-skip-errors=.*/slave-skip-errors=1062/" $MYSQL_CONF_FILE
+        sed -i "s/^log_bin_trust_function_creators=.*/log_bin_trust_function_creators=ON/" $MYSQL_CONF_FILE
+    fi
+
+    MD5_POS=`md5sum "$MYSQL_CONF_FILE" | awk '{print $1}'`
+
+    if [ "$MD5_PRE" != "$MD5_POS" ]; then
+        # Restart mysql
+        dpkg-trigger --no-await alienvault-restart-mysql
+    fi
+}
+
+set_grants() {
+    # If exists ossim_setup.conf_last set the last config from it
+    # If not exists set the last config equals to actual config
+    # If exists and the connection not works set the last config equals to actual config
+
+    set +e
+
+    echo "Setting DB grants..."
+
+    framework_ip=$(get_ossim_param_value "framework_ip")
+    server_ip=$(get_ossim_param_value "server_ip")
+    hostname=$(get_ossim_param_value "hostname")
+    admin_ip=$(get_ossim_param_value "admin_ip")
+    pass=$(get_ossim_param_value "pass")
+
+    if [ -f $OSSIM_SETUP_CONF_LAST ]; then
+        last_framework_ip=$(get_ossim_param_value "framework_ip" "last")
+        last_server_ip=$(get_ossim_param_value "server_ip" "last")
+        last_hostname=$(get_ossim_param_value "hostname" "last")
+        last_admin_ip=$(get_ossim_param_value "admin_ip" "last")
+        last_pass=$(get_ossim_param_value "pass" "last")
+
+        TEST_QUERY=`mysql -uroot -p$last_pass -e "SELECT 1" 2>&1`
+        ERROR=`echo $TEST_QUERY | grep -rni "ERROR"`
+    fi
+
+    if [ ! -z "$ERROR" ] || [ ! -z "${ERROR-NO_INSTANCE}" ]; then
+        last_framework_ip=$framework_ip
+        last_server_ip=$server_ip
+        last_hostname=$hostname
+        last_admin_ip=$admin_ip
+        last_pass=$pass
+    fi
+
+    mysql -uroot -p$last_pass -e \
+        "UPDATE mysql.user SET host=LOWER(host);
+        GRANT USAGE ON *.* TO root@'$last_framework_ip';
+        DROP USER root@'$last_framework_ip';
+        GRANT USAGE ON *.* TO ocs@'$last_framework_ip';
+        DROP USER ocs@'$last_framework_ip';
+        GRANT USAGE ON *.* TO root@'$last_admin_ip';
+        DROP USER root@'$last_admin_ip';
+        GRANT USAGE ON *.* TO root@'$last_server_ip';
+        DROP USER root@'$last_server_ip';
+        GRANT USAGE ON *.* TO root@'$last_hostname';
+        DROP USER root@'$last_hostname';
+        GRANT ALL ON *.* TO root@'$framework_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO ocs@'$framework_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$admin_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$server_ip' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'$hostname' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'127.0.0.1' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'localhost' IDENTIFIED BY '$pass';
+        GRANT ALL ON *.* TO root@'::1' IDENTIFIED BY '$pass';
+        FLUSH PRIVILEGES;"
+
+    set -e
+}
+
 configure_firewall(){
-    
+
     server_ip=$(get_ossim_param_value "server_ip")
     framework_ip=$(get_ossim_param_value "framework_ip")
 
@@ -55,7 +337,6 @@ configure_firewall(){
     fi
 
     dpkg-trigger --no-await alienvault-restart-firewall
-    
 }
 
 update_serverip_iptables(){
@@ -100,19 +381,34 @@ update_frameworkip_iptables(){
 case "$1" in
     configure)
         configure_firewall
+        reconfigure_mysql
     ;;
 
     triggered)
+        CHANGED_IF_GRANTS=0
+
         for trigger in $2
         do
             case "$trigger" in
                 alienvault-config-server-server-ip)
                     update_serverip_iptables
                     dpkg-trigger --no-await alienvault-restart-firewall
+                    CHANGED_IF_GRANTS=1
                     ;;
                 alienvault-config-framework-framework-ip)
                     update_frameworkip_iptables
                     dpkg-trigger --no-await alienvault-restart-firewall
+                    CHANGED_IF_GRANTS=1
+                    ;;
+                alienvault-config-ha-ha-heartbeat-start|alienvault-config-ha-ha-role)
+                    reconfigure_mysql
+                    ;;
+                alienvault-mysql-set-grants|alienvault-config-database-pass|alienvault-config-system-hostname|alienvault-config-system-admin-ip)
+                    CHANGED_IF_GRANTS=1
+                    ;;
+                alienvault-restart-mysql)
+		    stop_mysql
+		    start_mysql
                     ;;
                 *)
                     echo "postinst called with unknown trigger \`$2'">&2
@@ -120,6 +416,10 @@ case "$1" in
                     ;;
             esac
         done
+
+        if [ $CHANGED_IF_GRANTS -ne 0 ]; then
+            set_grants
+        fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/alienvault-dummies-config/debian/alienvault-ntop.postinst b/alienvault-dummies-config/debian/alienvault-ntop.postinst
--- a/alienvault-dummies-config/debian/alienvault-ntop.postinst
+++ b/alienvault-dummies-config/debian/alienvault-ntop.postinst
@@ -17,12 +17,13 @@ set -e
 # for details, see http://www.debian.org/doc/debian-policy/ or
 # the debian-policy package
 
-IPTABLES_CFG_FILE="/etc/iptables/rules011-ntop.iptables"
 OSSIM_SETUP_FILE="/etc/ossim/ossim_setup.conf"
 
 update_frameworkip_iptables(){
+    IPTABLES_CFG_FILE="/etc/iptables/rules011-ntop.iptables"
+
     # Updates sensor and db iptables files with the most recent framework ip value
-    framework_ip=$(grep "^framework_ip=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'framework_ip' parameter not found" && exit -1))
+    framework_ip=$(awk -F '=' '/\<framework_ip\>/ {print $2}' "$OSSIM_SETUP_FILE")
 
     if [ ${#framework_ip} != 0 ]; then
         sed -i "s/^#*//g" $IPTABLES_CFG_FILE
@@ -33,82 +34,73 @@ update_frameworkip_iptables(){
         else
             old_framework_ip=$(sed -n 1p $IPTABLES_CFG_FILE | cut -d' ' -f14)
             sed -i "s/$old_framework_ip/$framework_ip/g" $IPTABLES_CFG_FILE
-            
         fi         
     else
         sed -i "1 s/^/#/" $IPTABLES_CFG_FILE
     fi
 
+    dpkg-trigger --no-await alienvault-restart-firewall
 }
 
+configure_ntop(){
+    CFG_DIR="/var/lib/ntop"
+    INIT_CFG_FILE="$CFG_DIR/init.cfg"
+    INTERFACES=$(awk -F '=' '/\<interfaces\>/ {print $2}' "$OSSIM_SETUP_FILE" | tr -d ' ')
+    NETWORKS=$(awk -F '=' '/\<networks\>/ {print $2}' "$OSSIM_SETUP_FILE")
+
+    # Test for ntop configuration file
+    [ -f "$INIT_CFG_FILE" ] || touch $INIT_CFG_FILE
+
+    MD5_PRE=`md5sum "$INIT_CFG_FILE"|awk '{print $1}'`
+
+    # Change configuration parameters in its init file
+    cat >$INIT_CFG_FILE << EOF
+GETOPT="-M -t 1 --no-mac -m \"${NETWORKS}\" -g "
+INTERFACES="${INTERFACES}"
+USER="ntop"
+EOF
+
+    # Change permissions for ntop directories
+    find "$CFG_DIR" -type d -exec chmod g+x,g+w {} \; || true
+    find "$CFG_DIR" -type d -exec chgrp ntop {} \; || true
+
+    MD5_POS=`md5sum "$INIT_CFG_FILE"|awk '{print $1}'`
+
+    if [ "$MD5_PRE" != "$MD5_POS" ]; then
+        dpkg-trigger --no-await alienvault-ntop-restart
+    fi
+}
+
+configure_ntop_db_pass(){
+    DB_PASS=$(awk -F '=' '/\<pass\>/ {print $2}' "$OSSIM_SETUP_FILE")
+
+    # Update ntop password
+    ( /usr/sbin/ntop -u ntop -P"$CFG_DIR" --set-admin-password="$DB_PASS" > /dev/null 2>&1 ) || \
+        (echo "Cannot set Ntop password" && exit 0)
+}
+
+configure_ntop_db(){
+    FRAMEWORK_IP=$(awk -F '=' '/\<framework_ip\>/ {print $2}' "$OSSIM_SETUP_FILE")
+    
+    # Change ntop_link value in alienvault.config, if this system has also a 'server' profile.
+    IS_SERVER=$(grep "^profile=.*Server.*$" "$OSSIM_SETUP_FILE" || true)
+    if [ -x "/usr/bin/ossim-db" ] && [ -n "$IS_SERVER" ]; then
+        REPLACE_NTOP_LINK_QUERY="REPLACE INTO alienvault.config VALUES('ntop_link','http://$FRAMEWORK_IP:3000');"
+        echo "$REPLACE_NTOP_LINK_QUERY" | ossim-db || true
+    fi
+}
 
 case "$1" in
     configure)
-        CHANGED=0
-        CFG_DIR="/var/lib/ntop"
-        INIT_CFG_FILE="$CFG_DIR/init.cfg"
-        INTERFACES=$(grep "^interfaces=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'interfaces' parameter not found" && exit 0))
-        NETWORKS=$(grep "^networks=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'networks' parameter not found" && exit 0))
-        IS_MONITOR=$(grep "^monitors=.*ntop\-monitor.*$" "$OSSIM_SETUP_FILE" || (echo "'monitors' parameter not found" && exit 0))
-        DB_IP=$(grep "^db_ip=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'db_ip' parameter not found" && exit 0))
-        DB_PASS=$(grep "^pass=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'database pass' parameter not found" && exit 0))
-
-        if [ -n "$IS_MONITOR" ]; then
-           # Test for ntop configuration file
-           [ -f "$INIT_CFG_FILE" ] || (echo "Ntop configuration file $INIT_CFG_FILE does not exist" && exit 0)
-
-           MD5_PRE=`md5sum "$INIT_CFG_FILE"|awk '{print $1}'`
-
-           # Change configuration parameters in its init file
-           sed -i "$INIT_CFG_FILE" \
-               -e "s:^INTERFACES=.*:INTERFACES=\"$INTERFACES\":" \
-               -e "s:^GETOPT=.*:GETOPT=\"-M -t 1 --no-mac -m \\\"$NETWORKS\\\" -g \":"
-
-           # Change permissions for ntop directories
-           find "$CFG_DIR" -type d -exec chmod g+x,g+w {} \; || true
-           find "$CFG_DIR" -type d -exec chgrp ntop {} \; || true
-
-           MD5_POS=`md5sum "$INIT_CFG_FILE"|awk '{print $1}'`
-
-           if [ "$MD5_PRE" != "$MD5_POS" ]; then
-              CHANGED=1
-           fi
-
-           # Update ntop password
-           ( /usr/sbin/ntop -u ntop -P"$CFG_DIR" --set-admin-password="$DB_PASS" > /dev/null 2>&1 ) || \
-              (echo "Cannot set Ntop password" && exit 0)
-
-           if [ $CHANGED -ne 0 ]; then
-              dpkg-trigger --no-await alienvault-ntop-reload
-           fi
-
-           # Change iptables rule, if needed.
-           IS_DEFAULT_FIREWALL=$(grep "\-A INPUT  \-p tcp \-m state \-\-state NEW \-m tcp \-\-dport 3000 \-s FRAMEWORK\_IP \-j ACCEPT" "$IPTABLES_CFG_FILE" || true)
-           if [ -z "$IS_DEFAULT_FIREWALL" ]; then
-              FRAMEWORK_IP=$(grep "^framework_ip=.*" "$OSSIM_SETUP_FILE" | cut -d "=" -f 2 || (echo "'framework_ip' parameter not found"))
-              if [ ${#FRAMEWORK_IP} != 0 ]; then
-                  sed -i "s/^#*//g" $IPTABLES_CFG_FILE
-                  sed -i "s:FRAMEWORK_IP:$FRAMEWORK_IP:" "$IPTABLES_CFG_FILE"
-              else
-                  echo "ignoring ntop iptables rules since framework_ip parameter has not been found"
-                  sed -i "1 s/^/#/" $IPTABLES_CFG_FILE
-                  exit 0
-              fi
-              dpkg-trigger --no-await alienvault-restart-firewall
-           fi
-
-           # Change ntop_link value in alienvault.config, if this system has also a 'server' profile.
-           IS_SERVER=$(grep "^profile=.*Server.*$" "$OSSIM_SETUP_FILE" || true)
-           IS_MYSQL_RUNNING=$(nc -w1 "$DB_IP" 3306 2>&1 | grep -v "Connection refused$" || true)
-           if [ -x "/usr/bin/ossim-db" ] && [ -n "$IS_SERVER" ] && [ -n "$IS_MYSQL_RUNNING" ]; then
-              REPLACE_NTOP_LINK_QUERY="REPLACE INTO alienvault.config VALUES('ntop_link','http://$FRAMEWORK_IP:3000');"
-              echo "$REPLACE_NTOP_LINK_QUERY" | ossim-db
-           fi
-        fi
-
+        update_frameworkip_iptables
+	configure_ntop
+	configure_ntop_db_pass
+	configure_ntop_db
     ;;
 
     triggered)
+	CHANGED_IF_NET=0
+
         # Check if there's any trigger that shouldn't be there....
         for trigger in $2
         do
@@ -117,16 +109,27 @@ case "$1" in
                     /etc/init.d/ntop force-reload || true
                     update-rc.d ntop defaults
                 ;;
+		alienvault-config-database-pass)
+		    configure_ntop_db_pass
+		;;
                 alienvault-config-framework-framework-ip)
+		    configure_ntop_db
                     update_frameworkip_iptables
-                    dpkg-trigger --no-await alienvault-restart-firewall
                 ;;
+		alienvault-config-sensor-interfaces|alienvault-config-sensor-networks)
+		    CHANGED_IF_NET=1
+		;;
                 *)
                     echo "postinst called with unknown trigger \`$2'">&2
                     exit 1
                 ;;
             esac
         done
+
+	if [ $CHANGED_IF_NET -ne 0 ]
+	then
+	    configure_ntop
+	fi
     ;;
 
     abort-upgrade|abort-remove|abort-deconfigure)
diff --git a/os-sim/debian/ossim-server.init b/os-sim/debian/ossim-server.init
--- a/os-sim/debian/ossim-server.init
+++ b/os-sim/debian/ossim-server.init
@@ -17,7 +17,9 @@ PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
 DESC="OSSIM Server"
 NAME=ossim-server
 DAEMON=/usr/bin/$NAME
-PIDFILE=/var/run/alienvault/$NAME.pid
+RUNDIR=/var/run
+PIDDIR=$RUNDIR/alienvault
+PIDFILE=$PIDDIR/$NAME.pid
 SCRIPTNAME=/etc/init.d/$NAME
 RUNNING_INSTANCE_EXITS_E=2
 
@@ -60,6 +62,32 @@ d_start() {
         then
         log_daemon_msg "WARNING:Not starting $DESC, it has already been started."
         exit $RUNNING_INSTANCE_EXITS_E
+   fi
+
+   if [ ! -d $PIDDIR ]; then
+      mkdir -p -m 0770 "$PIDDIR"
+      chgrp -R alienvault "$PIDDIR"
+   fi
+
+   # Check if /var/run is a symbolic link to determine the Debian configuration
+   if [ -h $RUNDIR ]; then
+      # Wheezy
+      mount | grep "/run type" > /dev/null
+      if [ "$?" != "1" ]; then
+         if [ ! -d $PIDDIR ]; then
+            mkdir -p -m 0770 "$PIDDIR"
+            chgrp -R alienvault "$PIDDIR"
+         fi
+      else
+         log_daemon_msg "ERROR: /run is not mounted yet. The system is not stable. Skipping"
+         exit 1
+      fi
+   else
+      # Squeeze
+      if [ ! -d $PIDDIR ]; then
+         mkdir -p -m 0770 "$PIDDIR"
+         chgrp -R alienvault "$PIDDIR"
+      fi
    fi
 
    # If pidfile exists, we remove it before start.
