5.4.0 Soruce code (md5 = e29440ed0adeb5bab95ab0345ba5f324)

diff --git a/alienvault-dummies-config/debian/alienvault-nfsen.postinst b/alienvault-dummies-config/debian/alienvault-nfsen.postinst
--- a/alienvault-dummies-config/debian/alienvault-nfsen.postinst
+++ b/alienvault-dummies-config/debian/alienvault-nfsen.postinst
@@ -58,21 +58,33 @@ configure_nfsen() {
 }
 
 security_patch() {
-    # ENG-104863
-    REG_FILE="/usr/libexec/nfsen/Nfcomm.pm"
-    BACKUP="/usr/libexec/nfsen/Nfcomm.pm_backup"
-    PATCH="/usr/libexec/nfsen/security.patch"
 
-    # We should avoid applying the path if it has already been applied earlier
-    if ! grep -q "ENG-104863" ${REG_FILE}
+    nfsen_version_current=$( dpkg -l nfsen | awk '{ if ($2 ~ /nfsen/) print $3}' )
+    nfsen_version_vulnerable="2:1.3.7-1~bpo80+1"
+
+    if expr "${nfsen_version_current}" : "${nfsen_version_vulnerable}" &>/dev/null
         then
-                cp "$REG_FILE" "$BACKUP"
-                cd /
-                patch -p0 < "$PATCH" && echo "Patch successfully applied!" || echo "ERROR: Failed to apply patch!"
-                /usr/bin/nfsen reconfig
-        else
-                echo "Patching is not required."
+
+            # ENG-104863
+            REG_FILE="/usr/libexec/nfsen/Nfcomm.pm"
+            BACKUP="/usr/libexec/nfsen/Nfcomm.pm_backup"
+            PATCH="/usr/libexec/nfsen/security.patch"
+
+            echo "Currently installed version of nfsen has serious security vulnerability. Checking for a security patch..."
+
+            # We should avoid applying the patch if it has already been applied earlier
+            if ! grep -q "ENG-104863" ${REG_FILE}
+                then
+                        cp "$REG_FILE" "$BACKUP"
+                        cd /
+                        patch -p0 < "$PATCH" && echo "Patch successfully applied!" || echo "ERROR: Failed to apply patch!"
+                        /usr/bin/nfsen reconfig
+                else
+                        echo "Patching is not required."
+            fi
+
     fi
+
 }
 
 case "$1" in
